stages:
  - build
build image:
  image: 'docker:stable'
  services:
    - 'docker:dind'
  variables:
    COMMIT_SHA: '$CI_COMMIT_SHA:0:8'
    IMAGE_TAG: '$CI_REGISTRY_IMAGE:$COMMIT_SHA'
    DOCKER_HOST: 'tcp://docker:2375'
  stage: build
  only:
    - master
  tags:
    - docker
    - gce
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  script:
    - docker build --pull -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
