stages:
  - build
build image:
  image: 'docker:stable'
  services:
    - 'docker:dind'
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE
    DOCKER_HOST: 'tcp://docker:2375'
  stage: build
  only:
    - master
  tags:
    - docker
    - gce
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  script:
    - 'docker build --pull -t $IMAGE_NAME:${CI_COMMIT_SHA:0:8} .'
    - 'docker push $IMAGE_NAME:${CI_COMMIT_SHA:0:8}'
